@startuml
'https://plantuml.com/class-diagram

class Solution41{
+ArrayList<String> names
+String[][] arrOfstr
+String snakeOutput
+String badgerOutput
+String mushroomOutput
+int counterBadger
+int counterMushroom
+int counterSnake

+{static} {method} void main()

+{method} String[][] dataParser(): outputs 2d array for manipulation

+{method} void print()

+{method} String histogramCreator(): outputs strings for histogram
}
@enduml